version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: 
  

  